stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    continueOnError: true
    steps:
    - script: echo "hello to my Build"
- stage: Dev
  jobs:
  - job: Dev
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo "hello to my Dev"
- stage: qa_deploy
  jobs:
  - job: qa_deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo "hello, qa world !!!"
